## Data 결합

In [60]:
import numpy as np

In [75]:
list1 =[1,2,3]
a = np.array(list1)

In [76]:
a

array([1, 2, 3])

In [77]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [78]:
print(b.shape)
print(b[0,0])

(2, 3)
1


In [79]:
lst = [
    [1,2,3],
    [4,5,6],
    [7,8,9]
    ]
arr=np.array(lst)

In [80]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
a=arr[1:,1:]
print(a)

[[5 6]
 [8 9]]


In [68]:
a=arr[0:2,0:2]
print(a)

[[1 2]
 [4 5]]


In [69]:
bool_array =np.array([
    [False,True,False],
    [True,False,True],
    [False,True,False]
])

In [70]:
n=arr[bool_array];
print(n)

[2 4 6 8]


In [71]:
a=np.array(lst)
bool_indexing = (a % 2 == 0)
print(bool_indexing)
print(a[bool_indexing])

[[False  True False]
 [ True False  True]
 [False  True False]]
[2 4 6 8]


In [72]:
print(a[bool_indexing])
n = a[ a % 2 == 0]

[2 4 6 8]


In [81]:
c = a+b
c = np.add(a,b)
print(c)

[[2 4 6]
 [5 7 9]]


In [82]:
c=a-b
c=np.subtract(a,b)
print(c)

[[ 0  0  0]
 [-3 -3 -3]]


In [84]:
c=a-b
c=np.multiply(a,b)
print(c)

[[ 1  4  9]
 [ 4 10 18]]


In [85]:
c=a-b
c=np.divide(a,b)
print(c)

[[1.   1.   1.  ]
 [0.25 0.4  0.5 ]]


## 데이터의 결합

In [96]:
import pandas as pd
from pandas import Series, DataFrame

In [97]:
ar1=np.arange(4)
print(ar1)

[0 1 2 3]


In [98]:
ar1=np.arange(4).reshape(2,2)
print(ar1)

[[0 1]
 [2 3]]


In [100]:
np.concatenate([ar1,ar1],axis=0)

array([[0, 1],
       [2, 3],
       [0, 1],
       [2, 3]])

In [107]:
df1 = DataFrame({'a':[1,2,3],'b':[4,5,6]})

In [112]:
df1

a  b
0  1  4
1  2  5
2  3  6

In [117]:
df2=DataFrame({
    'a':[10,11],
    'b':[40,50]
})


In [118]:
df2

a   b
0  10  40
1  11  50

In [119]:
df3=DataFrame({
    'a':[40,50,60],
    'b':[70,80,90],
    'c':[10,11,12]
})


In [120]:
df3

a   b   c
0  40  70  10
1  50  80  11
2  60  90  12

In [121]:
pd.concat([df1,df2])

a   b
0   1   4
1   2   5
2   3   6
0  10  40
1  11  50

In [122]:
pd.concat([df1,df2],axis=1)

a  b     a     b
0  1  4  10.0  40.0
1  2  5  11.0  50.0
2  3  6   NaN   NaN

In [134]:
pd.concat([df1,df2],axis=1)
pd.concat([df1,df2],axis=1,join='inner',keys=['one','two'])

one    two    
    a  b   a   b
0   1  4  10  40
1   2  5  11  50

In [137]:
df1 = DataFrame({'A':[1,2,3,4],'B':[5,6,7,8], 'C':[9,10,11,12]})

In [138]:
df1

A  B   C
0  1  5   9
1  2  6  10
2  3  7  11
3  4  8  12

In [151]:
df2 = DataFrame({'A':['a','b','c','d'],'D':['e','f','g','h'], 'F':['i','j','k','l']})

In [152]:
df2

A  D  F
0  a  e  i
1  b  f  j
2  c  g  k
3  d  h  l

In [153]:
df1.combine_first(df2)

A  B   C  D  F
0  1  5   9  e  i
1  2  6  10  f  j
2  3  7  11  g  k
3  4  8  12  h  l